FROM jupyter/minimal-notebook

CMD ["jupyter", "notebook", "-y", "--generate-config"]
CMD ["jupyter", "notebook", "--NotebookApp.token=''","--NotebookApp.password=''", "--allow-root", "--no-browser"]


