apiVersion: v1
kind: Service
metadata:
  name: spark-service
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: spark
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-service
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: sonar
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: project
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: jupyter
